site_name: Arista Campus Networking Demo
site_description: Arista Validated Design (AVD) Campus Deployment & Operations Demo
site_author: Arista CE Southwest
site_url: https://arista-ce-southwest.github.io/avd-campus-networking-event-demo/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: blue
  icon:
    logo: material/network
    repo: fontawesome/brands/github

repo_url: https://github.com/arista-ce-southwest/avd-campus-networking-event-demo
repo_name: arista-ce-southwest/avd-campus-networking-event-demo
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Topology Overview: topology.md
  - Automation Workflow: workflow.md
  - AVD Variables and Data Model: variables.md
  - AVD Environment Setup: setup.md
  - Documentation: 
      - Fabric:
          - CAMPUS Documentation: documentation/fabric/CAMPUS-documentation.md
      - Device:
          - SC-B1-Core1: documentation/devices/SC-B1-Core1.md
          - SC-B1-Core2: documentation/devices/SC-B1-Core2.md
          - SC-B1-IDF1: documentation/devices/SC-B1-IDF1.md
  - References: references.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2

extra:
  copyright: "Copyright &copy; 2019 - 2025 Arista Networks"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arista-ce-southwest/avd-campus-networking-event-demo
  mermaid: true
