name: Deploy MkDocs Site

on:
  push:
    branches:
      - docs-preview   # testing branch
      # - main         # uncomment when ready for public site

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r git-pages-req.txt

      - name: Build MkDocs site
        run: |
          mkdocs build --clean --strict --site-dir site
          touch site/.nojekyll   # disable Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
